package kh.java.Exception;

public class ExceptionDemo2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int data1 = 10;
		int data2 = 0;
		int result;
		ExceptionTest t = null;	//래퍼런스 생성 (객체는 없음)
//		System.out.println(data1/data2);
//		t.start();
//		int [] arr = new int[-10];
//		int [] arr2 = new int[5];
//		arr2[5] = 100;
	}

}
